### ISSUE TITLE
Connection drops after a while

### ISSUE THREAD

**Issue by tleydxdy** [gordboy/rtl8812au-5.9.3.2#23] opened 2021-08-15 00:17 UTC
There are no errors in dmesg, but the connection will stop working. pinging the gateway will show host not reachable but otherwise the interface seems up. restarting systemd-networkd or iwd does not appear to be able to fix the issue (the interface will just keep trying to go UP and fail). Unplug and re-plug the adapter fixes the issue.

kernel is 5.13.9-arch1-1 using the AUR git package. adapter is as follows
Bus 005 Device 036: ID 0bda:8812 Realtek Semiconductor Corp. RTL8812AU 802.11a/b/g/n/ac 2T2R DB WLAN Adapter

**Comment by gordboy** [comment] 2021-08-21 19:33
Not sure what the problem is here. I will see what I can find out myself with some more testing.

**Comment by gordboy** [comment] 2021-08-22 12:19
The 5.13 kernel seems to have broken this driver somewhat. I get the same thing. It builds fine, dmesg is clear, and yet the same issues. Very strange.

**Comment by yichangshengwu** [comment] 2021-08-22 17:06
Hardware：Tenda U12，
Kernel: Linux 5.13.12-zen1-1-zen，
using this driver by git clone > install，
sometimes network does‘t response while it seems normally connected，but not often，
and everytime the network is unresponsive， run ‘sudo systemctl restart NetworkManager’ will make things normal，
so weird

**Comment by gordboy** [comment] 2021-09-01 12:46
Have a look at this -

https://github.com/morrownr/USB-WiFi

**Comment by tleydxdy** [comment] 2021-09-04 16:00
it seems like the drop has something to do with usb autosuspend

**Comment by gordboy** [comment] 2021-09-04 18:32
Right that makes sense. I think I am not going to attempt to fix that in the code. If Realtek fix it then fine.

It feels like a good time to move to another Wifi solution based on the mt7610u or similar. I highly recommend the outstanding article I linked above by @morrownr.

**Comment by morrownr** [comment] 2021-09-05 18:19
> If Realtek fix it then fine.
> 

It has been about a year since we have seen anything from Realtek. This driver is based on that latest release. Other chipsets seem to be left out in the cold. The most recent driver for the 8814au chipset is from 2019 and it was not a good driver. We have been able to patch a few things in the 8814au driver and in some of the other modern dual band Realtek drivers but it is getting harder to do as time marches on and there are just some major capabilities that we just can't do here in the community. We just can't get there as far as WPA3 is concerned. Realtek just seems not to care.

On the other hand, all of the in-kernel drivers are in really good shape. WPA3 is supported and there are a lot of adapters on the market that use the in-kernel mt76 driver. Mediatek does care and does it right. We can report bugs. The drivers are constantly updated and new versions are released with each new kernel release. Sometimes I see users of one of the Realtek drivers get an adapter based on a Mediatek chipset. The report I usually get is something like this:

"Wow. I plugged it in and it worked. It does what I need and now I can finish the project I was working on" And then I never hear from them again.

I've put a lot of work into [USB-WiFi](https://github.com/morrownr/USB-WiFi) because I saw what Linux users were having to put up with regarding the Realtek drivers. There are plenty of usb wifi adapters that use good in-kernel drivers, it was simply a matter of researching and providing the information about what adapters and where they can be purchased.

Gord, thanks for passing on the info.

**Comment by gordboy** [comment] 2022-01-28 14:45
Not maintaining this repo any further. There are better devices and drivers.

**Closed as completed by gordboy** 2022-01-28 14:45 UTC

**Comment by LorenzoAncora** [comment] 2022-01-28 15:09
> Not maintaining this repo any further.

@gordboy then you should [**archive**](https://docs.github.com/en/repositories/archiving-a-github-repository/archiving-repositories) this repository. Thank for putting effort since 2018. 👍🏻 

> There are better devices and drivers.

So, the current end users of `rtl8812au-5.9.3.2` should start using [this repository](https://github.com/morrownr/8812au-20210629) instead?
